version: "{build}"

os: Visual Studio 2015

clone_depth: 50

environment:
  matrix:
    # Visual Studio 2015 64bit
    - visualcpp: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
  machine: amd64
install:
  - cinst winflexbison
  - cinst -PackageParameters InstallDevelopmentHeaders=true imagemagick
  - refreshenv
  - call "%visualcpp%" %machine%
init:
  - call "%visualcpp%" %machine%
  - set YACC=win_bison
build_script:
 - cd ..
 - git clone https://github.com/mruby/mruby.git
 - cd mruby
 - set MRUBY_CONFIG=..\mruby-mrmagick\appveyor_config.rb
 - set path="c:\program files\ImageMagick-7.0.7-Q16";%path%
 - where convert
 - where composite
 - where identify
 - rake all test
 
