version: "{build}"

os: Visual Studio 2015

clone_depth: 50

environment:
  matrix:
    # Visual Studio 2015 64bit
    - visualcpp: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
  machine: amd64
install:
  - cinst winflexbison
  - cinst -PackageParameters InstallDevelopmentHeaders=true imagemagick
  - refreshenv
  - dir "C:\Program Files\ImageMagick-7.0.7-Q16"
  - call "%visualcpp%" %machine%
init:
  - call "%visualcpp%" %machine%
  - set YACC=win_bison
build_script:
 - cd ..
 - git clone https://github.com/mruby/mruby.git
 - cd mruby
 - set MRUBY_CONFIG=..\mruby-mrmagick\appveyor_config.rb
 - rake --trace all 
 - dir build\host\bin\
 - build\host\bin\mruby --version
 
